[package]
name = "libempire"
version = "0.1.0"
authors = ["Andrew Gaspar <andrew.gaspar@outlook.com>"]

[lib]
name = "empire"
crate-type = ["cdylib"]

[dependencies]
empire = { path = "../empire" }
conv = "0.3"
itertools = "0.7.3"