[package]
name = "empire"
version = "0.1.0"
authors = ["Andrew Gaspar <andrew.gaspar@outlook.com>"]

[dependencies]
tokio = "0.1"
tokio-process = { git = "https://github.com/alexcrichton/tokio-process.git" }
futures = "0.1"